//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a1ea5a2f6) on 2025-01-14 16:53:04
//--------------------------------------------------------------------------------
#ifndef __GENERATED_GIT_H
#define __GENERATED_GIT_H

#define LITEX_GIT_SHA1 "a1ea5a2f6"
#endif
